[project]
name = "serein"
version = "0.1.0"
description = "A tool to manage your Serein desktop environment."
authors = [{ name = "Nixuris", email = "nixuriss@proton.me" }]
dependencies = [
    "click",
]

[project.scripts]
serein-py = "serein.main:cli"
