#!/usr/bin/env bash

# GDK BACKEND. Change to either wayland or x11 if having issues
BACKEND=wayland

# Check if rofi or yad is running and kill them if they are
if pidof rofi > /dev/null; then
  pkill rofi
fi

if pidof yad > /dev/null; then
  pkill yad
fi

# Launch yad with calculated width and height
GDK_BACKEND=$BACKEND yad \
    --center \
    --title="Iris's Keybinds" \
    --no-buttons \
    --list \
    --column=Key: \
    --column=Description: \
    --column=Command: \
    --timeout-indicator=bottom \
"ESC" "close this app" "" " = " \
"SUPER KEY (Windows Key Button)" "(SUPER KEY)" \
" L" "Launches Session Manager" "Rofi" \
"" "" "" \
" H" "Launch this keybind list" "" \
" Enter" "Terminal" "(alacritty)" \
" Q" "close window" "(not kill)" \
" F" "Fullscreen" "Toggles to full screen" \
" W" "Toggle float" "single window" \
" 1-10" "Switch Between Workspaces" "single window" \
" Shift 1-10" "Move Windows to Workspaces" "" \
" ↑↓→←" "Focus Windows" "single window" \
" CTRL ↑↓→←" "Move Windows To Directions" "single window" \
" LMB" "Grab Windows" "single window" \
" RMB" "Resize Windows" "single window" \
"" "" "" \
" Shift Q " "kills an active window" "(single window)" \
" N" "show notifications" "(swaync)" \
" S" "Hidden Workspace" "Separate from original workspaces" \
" ALT S" "Move To Hidden Workspace" "Move window from original workspace to special workspace" \
"" "" "" \
" SPACE" "Application Launcher" "(rofi-wayland)" \
" V" "Clipboard Manager" "CTRL + DEL to delete one entry || SUPER + DEL to wipe all history" \
" Period" "Emoji to clipboard" "(cliphist + rofi)" \
" Shift S" "screenshot region" "(swappy)" \
" Shift W" "Choose wallpaper" "(imagemagick + swww)" \
" R" "Close / open waybar" "Activate waybar when its not there and vice versa" \
"" "" "" \
" P" "View processes" "(htop)" \
" T" "Open File Manager" "(ranger)" \
"ALT S" "Local TUI Music Player" "(cmus)" \
"" "" "" \
